name: linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Dependencies
        run: |
          sudo apt-get install aspell aspell-en
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Run Pint
        run: vendor/bin/pint

      - name: Run Larastan
        run: vendor/bin/phpstan analyse --memory-limit=2G

      - name: Run Peck
        run: vendor/bin/peck

      - name: Format Frontend
        run: npm run format

      - name: Lint Frontend
        run: npm run lint
